GET http://localhost:3000/users

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/2

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "nickname": "banana",
    "password": "password1234",
    "confirm": "password1234"
}

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "banana milk",
    "content": "is great",
    "userId": 1
}

###

PATCH http://localhost:3000/posts/2
Content-Type: application/json

{
    "title": "strawberry milk",
    "content": "is great"
}

###

DELETE  http://localhost:3000/posts/2
