GET http://localhost:3000/posts/test

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/3

###

GET http://localhost:3000/comments/3

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "nickname": "pear",
    "password": "password1234",
    "confirm": "password1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "nickname": "pear",
    "password": "password1234"
}

###

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFwcGxlIiwiaWF0IjoxNjczMTkxMTY3fQ.ttir7edF_ur_OjXPIQTkAFq_MmyeyjCPstuWNS21dTM

{
    "title": "saturday",
    "content": "is great"
}

###

POST http://localhost:3000/comments/3
Content-Type: application/json

{
    "content": "java",
    "userId": "1"
}

###

###

POST http://localhost:3000/posts/5/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InBlYXIiLCJpYXQiOjE2NzMxOTE2NjF9.bs55K4_uLCruAahuQROomgb7p0NRNvO_IyqbFX39dKY

###

PATCH http://localhost:3000/posts/2
Content-Type: application/json

{
    "title": "strawberry milk",
    "content": "is great"
}

###

PATCH http://localhost:3000/comments/2
Content-Type: application/json

{
    "content": "ruby"
}

###

DELETE  http://localhost:3000/posts/2

###

DELETE  http://localhost:3000/comments/4